# Generated by Django 3.2.4 on 2021-08-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_classroom', '0004_userprofile_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_teacher',
        ),
    ]
