# Generated by Django 3.2.4 on 2021-07-04 14:20

import courseMaterials.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseMaterials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=30, unique=True, verbose_name='Course ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=courseMaterials.models.courseImage, verbose_name='Course Image')),
                ('description', models.TextField(blank=True, max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courseMaterials.semester')),
            ],
        ),
    ]
