# Generated by Django 3.2.4 on 2021-07-05 12:25

import courseMaterials.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseMaterials', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leectureName', models.CharField(max_length=50, unique=True, verbose_name='Lecture/File Name')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter Number:')),
                ('pdf', models.FileField(blank=True, upload_to=courseMaterials.models.chapterFles, verbose_name='Upload PDF Files')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseMaterials.semester')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Faculty Name')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courseMaterials.course')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
