# Generated by Django 3.2.4 on 2021-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseMaterials', '0004_semester_semid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semID',
            field=models.IntegerField(max_length=3, unique=True, verbose_name='Semester ID'),
        ),
    ]
