# Generated by Django 3.2.4 on 2021-07-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseMaterials', '0006_alter_lecture_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courseMaterials.course', verbose_name='Course'),
        ),
    ]
