# Generated by Django 3.2.4 on 2021-07-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseMaterials', '0007_alter_lecture_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='askQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(blank=True, max_length=60)),
                ('comment_box', models.TextField(blank=True, max_length=300)),
                ('date_of_question', models.DateTimeField(auto_now_add=True)),
                ('lecture_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='askquestions', to='courseMaterials.lecture')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_question'],
            },
        ),
    ]
