# Generated by Django 3.2.4 on 2021-08-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseMaterials', '0008_askquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
