# Generated by Django 3.2.4 on 2021-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseMaterials', '0009_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
