# Generated by Django 3.2.6 on 2021-09-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210911_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lectures',
        ),
    ]
